wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/",views.addentry,name = "addentry"),
    path("wiki/<str:title>",views.getentry ,name="getentry"),
    path("random",views.randomentry,name="random"),
    path("search",views.searchentry,name="search"),
    path("edit/",views.editentry,name="editentry")
    
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
# Imports
from django.shortcuts import render
from django import forms
from . import util
import random 
import markdown2

# Class to create a form to add an entry
class NewEntry(forms.Form):
    # title
    title = forms.CharField(max_length=100,widget=forms.TextInput(attrs={
            'class':'form-control', 'id':'input',
            'placeholder':'Enter title'
                 }))
    # content
    content = forms.CharField(widget=forms.Textarea(attrs={
            'class': 'form-control','id':'content',
            'rows':10,'cols':150,'placeholder':'Enter markdown content'
    }))
    
# index page list all enteries
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })

# Get entry by its title . If a match is found,returns its markdown content ,convert it into html using markdown_content function ,then displays it . 
# Otherwise  returns an no entry found response.
def getentry(request,title):
        markdowncontent = util.get_entry(title.lower())
        if markdowncontent:
            Content=markdown_content(markdowncontent)
            return render(request,"encyclopedia/entry.html",{
                "data":Content,
                "title":title
            }
            ) 
        else:
                            
            return render(request,"encyclopedia/response.html",{
               "response":" Error: No such entry exists❌"
            }
            )

# Function to convert markdown content to Html
def markdown_content(content):
     return markdown2.markdown(content)

# Function to add an entry
# if the entry already exists, the entry is not saved and returns an error response.
# Otherwise Saves the new entry
def addentry(request):

    if request.method=="POST":
        entry = NewEntry(request.POST)
    # if the file already exists,shows error response
        if entry.is_valid():
            title = entry.cleaned_data["title"]
            content = entry.cleaned_data["content"]
            if util.get_entry(title):
                return render(request,"encyclopedia/response.html",{
                     "response": " Error: Cannot add entry: Entry already exists❗"
                })
    #  adds new entry
            else:
                 util.save_entry(title,content)
                 return render(request,"encyclopedia/response.html",{
                     "response": "Entry Saved😊"
                })
                 
                 
                 
    else:
                
            new = NewEntry()
            return render(request,'encyclopedia/add.html',{
                "new":new

            })

# Opens a  Random entry
def randomentry(request):
     entry = random.choice(util.list_entries())
     return  getentry(request,entry)
# Searches for an entry . If an exact match is found, the entry is displayed,otherwise the matching search results ar displayed
def searchentry(request):
    result=[]
    if request.method=="POST":
        title = request.POST.get("q")
        markdowncontent=util.get_entry(title)
        if markdowncontent:
            htmlcontent= markdown_content(markdowncontent)
            return render(request,"encyclopedia/entry.html",{
                "data":htmlcontent
            }
            )
        else:
            enteries= util.list_entries()
            for list in enteries :
                if title.lower() in list.lower():
                    result.append(list) 
                    
            
            if not result:
                 return render(request,"encyclopedia/response.html",{
                      "response":"No result found"
                 })      
            else:
                 return render(request,"encyclopedia/search.html",{
                      "searchresult":result
                 })

# Edit an existing entry

def editentry(request):
    if request.method=="POST":
         title=request.POST.get("title")
         content =request.POST.get("content")
         util.save_entry(title,content)
         return render(request,"encyclopedia/response.html",{
              "response": "Changes saved😊"
         })
    else:
        title= request.GET.get("filename")
        content=util.get_entry(title)
        return render(request,"encyclopedia/edit.html",{
            "title": title,
            "content":content
        })
     
               
          
     
          

wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}
  <!-- Add a new entry -->
{% block body %}
<!-- Normal page heading -->
    <div class="pagecontent">
        <div class="heading">
            <h2>Add page</h2>
        </div>

        <!-- Area to add data -->
        <div class="area">
            <form action="{%url 'encyclopedia:addentry' %}" method="POST">
                {% csrf_token %}

                <!-- Add Title -->
                <div class="titlearea">
                    <label for="title" id="input" class="label">Title</label>
                    {{new.title}}
                </div>

                <!--  Add Content  -->
                <div class="contentarea" >
                    <label for="content" id="content" class="label"> Content</label>
                    {{new.content}}
                </div>
            
                <!-- Submit Button  -->
                <div class="submit">
                <input type="submit" class="btn btn-primary btn-sm" value="Add page">
                </div>
        </form>
        </div>
    </div>
    
    
    {% endblock %}        

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
<!-- Edit an existing page/entry -->
{% block body %}

<!-- title : edit entry -->
<div class="pagecontent">
    <div class="heading">
       <h2>Edit Entry</h2>
    </div>

    <!-- Form to edit a entry -->
    <form action="{% url 'encyclopedia:editentry'%}" method="POST">
    {% csrf_token %}

    <!-- Heading section -->
    <div class="area">
        <div class="titlearea">
        <label for="Input" id="input" class="label">Title</label>
        <input type="text"  id ="input"  name="title" value="{{title}}" class="form-control" placeholder="Title">  
    </div>

    <!-- Content area -->
    <div class="contentarea" >
      <label for="content" id="content" class="label"> Content</label>
      <textarea class="form-control " id ="content" rows="10" cols="150" name="content"  > {{content}}</textarea>
    </div>

    <!-- Submit Button  -->
    <div class="submit">
        <input type="submit" class="btn btn-primary btn-sm" value="Save changes">
    </div>
   
</form>
</div>
    </div>
    

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
<!-- Displays the content of a given entry -->
{% block nav %}
<!-- Edit button to edit an entry -->
     <div class="editpage">
     <form action="{% url 'encyclopedia:editentry'%}" >
     {% csrf_token%}
     <input type="hidden" name="filename" value = "{{title}}">
     <input type="submit" class="btn btn-primary btn-sm " value="Edit entry">
     
     </form>
     </div>

{% endblock %}
{% block body %}
<!-- Content of the page -->
     <div class="content">
          <div class="data">
               {{data|safe}}
          </div>
     </div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}
<!-- Displays all enteries available -->
{% block title %}
    Encyclopedia
{% endblock %}


{% block body %}
<!-- Heading -->
    <h1 class="heading">All Entries</h1>
<!-- Entry list with links to directly open them  -->
    <ul class="entries">
        {% for entry in entries %}
            <li class="list-group-item"> <a href="wiki/{{entry}}"> {{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}
<!-- layout for all pages -->
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous" >
        <link rel="stylesheet" href="{% static 'encyclopedia/styles.css' %}" >
    </head>
    <body >
        <!-- Sidebar  -->
        <div class="customdiv">

        <div class="links">
            <!-- Logo -->
            <div class="image">
                <img src="{% static 'encyclopedia/logo.png'%}" height="250px" width="250px" alt="Wikipedia image">
            </div>

            <!-- Search bar -->
            <form action="{% url 'encyclopedia:search' %}" method="POST">
                {% csrf_token %}
                <input class="searchbar" type="text" name="q" placeholder="Search Encyclopedia">
            </form>

            <!-- Nav links -->
             
            <div class="navbar">
                <a class="nav-link" href="{% url 'encyclopedia:index' %}">Home</a>
            </div>

            <div class="navbar">
                <a class="nav-link" href="{% url 'encyclopedia:addentry' %}">Create New Page</a>
            </div>

            <div class="navbar">
                <a class="nav-link active" href="{% url 'encyclopedia:random' %}">Random Page</a>
            </div>
        </div>
            <!-- Vertical ruler to separate sidebar and page content -->
            <div class="vr"></div>

           <!--Body block and nav block to be inherited by child templates  -->
        <div class="pages">
            {% block nav %}{% endblock %}
            {% block body %}{% endblock %}
        </div>
    </div>
    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/response.html
{% extends "encyclopedia/layout.html" %}
  <!-- Response message if a page or entry is not found or if 
    someone tries to add an entry that already exists -->
{% block body %}
    <div class="result">
        <!-- response message -->
        <p class="message">
            {{response}}
        </p>
        <!-- Link to back to home page -->
        <p class="messgae">
            <a href="{% url 'encyclopedia:index' %}" class="goback">Go back</a>
        </p>
    </div>
    
    {% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}
<!--  Matching Search results for a query if no exact match is found -->
{% block body %}


    <div class="result">
        <h2 class="heading">Search Results...</h2>
        <!-- Display search results as links to access them directly
                Uses an unordered list, list items and anchor tags -->
        <ul class="list">
             {% for result in searchresult %}
             <li class="listitem"><a href="wiki/{{result}}">{{result}}</a></li>

             {% endfor %}
       
        </ul>
           
    </div>


{% endblock %}